# The progenitor. This should only container the most basic components possible.
# Only put things on here if every mob *must* have it. This includes ghosts.
- type: entity
  save: false
  id: BaseMob
  abstract: true
  components:
  - type: Sprite
    noRot: true
    drawdepth: Mobs
  - type: MobCollision
  - type: Physics
    bodyType: KinematicController
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 50
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Clickable
  - type: InteractionOutline
  - type: InputMover
  - type: Input
    context: "human"
  - type: LagCompensation
  - type: MobMover
  - type: Actions
  - type: Alerts
  - type: Appearance
  - type: RotationVisuals
    defaultRotation: 0
    horizontalRotation: 0
  - type: DoAfter
  - type: Examiner
  - type: Eye
  - type: ContentEye
  - type: CameraRecoil
  - type: MindContainer
  - type: MovementSpeedModifier
  - type: RequireProjectileTarget
    active: False

- type: entity
  save: false
  id: MobPolymorphable
  abstract: true
  components:
  - type: Polymorphable

# Used for mobs that have health and can take damage.
- type: entity
  save: false
  id: MobDamageable
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 1500
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: RadiationReceiver
  - type: Stamina
  - type: MobState
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Critical
      200: Dead
  - type: MobStateActions
    actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
  - type: Deathgasp
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
    - Asphyxiation
    - Radiation
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Pullable
  - type: LightningTarget
    priority: 2
    lightningExplode: false

# Used for mobs that can enter combat mode and can attack.
- type: entity
  save: false
  id: MobCombat
  abstract: true
  components:
  - type: CombatMode
  - type: MeleeWeapon
    hidden: true
    soundHit:
      collection: MetalThud
    damage:
      groups:
        Brute: 5

# Used for mobs that are affected by atmospherics, pressure, and heat
- type: entity
  save: false
  id: MobAtmosExposed
  abstract: true
  components:
  - type: AtmosExposed
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 0
    currentTemperature: 310.15
    coldDamage: #per second, scales with temperature & other constants
      types:
        Cold : 0.1
    specificHeat: 42
    heatDamage: #per second, scales with temperature & other constants
      types:
        Heat : 1.5
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 2
  - type: MovedByPressure

# Used for mobs that require regular atmospheric conditions.
- type: entity
  parent: MobAtmosExposed
  id: MobAtmosStandard
  abstract: true
  components:
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 250
    sweatHeatRegulation: 500
    shiveringHeatRegulation: 500
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 2
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
    coldDamage:
      types:
        Cold: 1 #per second, scales with temperature & other constants
    heatDamage:
      types:
        Heat: 1.5 #per second, scales with temperature & other constants
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.15 #per second, scales with pressure and other constants.

# Used for mobs that can be set on fire
- type: entity
  save: false
  id: MobFlammable
  abstract: true
  components:
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage: #per second, scales with number of fire 'stacks'
      types:
        Heat: 1.5
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning

# Used for mobs that need to breathe
- type: entity
  save: false
  id: MobRespirator
  abstract: true
  components:
  - type: Internals
  - type: Respirator
    damage:
      types:
        Asphyxiation: 2
    damageRecovery:
      types:
        Asphyxiation: -1.0

# Used for mobs that have a bloodstream
- type: entity
  save: false
  id: MobBloodstream
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: InjectableSolution
    solution: chemicals
  - type: Bloodstream
    bloodlossDamage:
      types:
        Bloodloss: 0.5
    bloodlossHealDamage:
      types:
        Bloodloss: -1

- type: entity
  id: BaseUniqueMob
  description: You're the only one of you in the whole sector! Hopefully.
  abstract: true
  components:
  - type: NameIdentifier
    # Unique mobs do not have a name identifier, even if their parent entity does.
    group: Disabled
  - type: Grammar
    attributes:
      # Unique mobs have a proper noun for a name.
      proper: true
      # Unique animals are not it/its unless specified.
      gender: epicene

- type: entity
  save: false
  parent:
  - BaseMob
  - MobDamageable
  - MobPolymorphable
  id: BaseSimpleMob
  suffix: AI
  abstract: true
  components:
  - type: Reactive
    groups:
      Flammable: [Touch]
      Extinguish: [Touch]
      Acidic: [Touch, Ingestion]
  - type: Internals
  - type: MovementSpeedModifier
    baseWalkSpeed : 4
    baseSprintSpeed : 4
  - type: StatusEffects
    allowed:
    - SlowedDown
    - Stutter
    - Electrocution
    - TemporaryBlindness
    - Pacified
    - Flashed
    - RadiationProtection
    - Adrenaline
  - type: Buckle
  - type: StandingState
  - type: Tag
    tags:
    - DoorBumpOpener

- type: entity
  abstract: true
  parent:
  - BaseSimpleMob
  - MobAtmosExposed
  - MobCombat
  - MobBloodstream
  - MobFlammable
  id: SimpleSpaceMobBase # Mob without barotrauma, freezing and asphyxiation (for space carps!?)
  suffix: AI
  components:
  - type: NpcFactionMember
    factions:
    - SimpleNeutral
  - type: HTN
    rootTask:
      task: IdleCompound
  - type: MeleeWeapon
    angle: 0
    animation: WeaponArcBite
  - type: Body
    prototype: Animal
  - type: Climbing
  - type: NameIdentifier
    group: GenericNumber
  - type: SlowOnDamage
    speedModifierThresholds:
      60: 0.7
      80: 0.5
  - type: MobPrice
    price: 1000 # Living critters are valuable in space.
  - type: Perishable

- type: entity
  parent:
  - MobRespirator
  - MobAtmosStandard
  - SimpleSpaceMobBase
  id: SimpleMobBase # for air breathers
  suffix: AI
  abstract: true
  components:
  - type: Hunger
    thresholds: # only animals and rats are derived from this prototype so let's override it here and in rats' proto
      Overfed: 100
      Okay: 50
      Peckish: 25
      Starving: 10
      Dead: 0
    baseDecayRate: 0.00925925925926 # it is okay for animals to eat and drink less than humans, but more frequently
  - type: Thirst
    thresholds:
      OverHydrated: 200
      Okay: 150
      Thirsty: 100
      Parched: 50
      Dead: 0
    baseDecayRate: 0.04
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - Electrocution
    - TemporaryBlindness
    - Pacified
    - StaminaModifier
    - Flashed
    - RadiationProtection
    - Adrenaline
  - type: Bloodstream
    bloodMaxVolume: 150
  - type: MobPrice
    price: 150
  - type: FloatingVisuals

# Used for generic robotic entities (like Hivelords)
- type: entity
  save: false
  abstract: true
  parent: BaseMob
  id: MobRobotic
  components:
  - type: Reactive
    groups:
      Acidic: [Touch]
  - type: Damageable
    damageContainer: Inorganic
  - type: MovedByPressure
  - type: Physics
    bodyType: KinematicController # Same for all inheritors
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - Electrocution
  - type: Repairable
    doAfterDelay: 8
    fuelCost: 15
  - type: Pullable
  - type: Tag
    tags:
    - DoorBumpOpener
    - SiliconEmotes
    - Unimplantable
  - type: MobState
    allowedStates:
      - Alive
      - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      120: Dead
    stateAlertDict:
      Alive: BorgHealth
      Dead: BorgDead
    showOverlays: false
  - type: Speech
    speechVerb: Robotic
    speechSounds: Borg
  - type: TypingIndicator
    proto: robot
  - type: Vocal
    sounds:
      Unsexed: UnisexSilicon
  - type: Emoting
  - type: ZombieImmune
  - type: ProtectedFromStepTriggers
  - type: NoSlip
  - type: Insulated

# Used for bots
- type: entity
  save: false
  abstract: true
  parent: MobRobotic
  id: MobSiliconBase
  components:
  - type: NpcFactionMember
    factions:
    - SimpleNeutral
  - type: Access
    tags:
    - BasicSilicon
  - type: IntrinsicRadioReceiver
  - type: ActiveRadio
    channels:
    - Common
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    locPrefix: silicon
  - type: NameIdentifier
    group: Silicon
  - type: MovementSpeedModifier
    baseWalkSpeed : 3
    baseSprintSpeed : 4
  - type: Stamina
    critThreshold: 120
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:TriggerBehavior
    - trigger:
        !type:DamageTrigger
        damage: 120
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: GuideHelp
    guides:
    - Robotics
  - type: Tag
    tags:
    - DoorBumpOpener
    - SiliconEmotes
    - Bot
    - Unimplantable
  - type: Body
    prototype: Bot
  - type: Speech
    speechVerb: Robotic
    speechSounds: Pai #couldn't decide if this should be borg or pai sounds so I flipped a coin.

- type: entity
  name: genetic ancestor
  id: MobBaseAncestor
  parent: [SimpleMobBase, StripableInventoryBase]
  description: The genetic bipedal ancestor of... Uh... Something. Yeah, there's definitely something on the station that descended from whatever this is.
  abstract: true
  components:
  - type: CombatMode
  - type: Inventory
    templateId: monkey
    speciesId: monkey
  - type: Deathgasp
    prototype: MonkeyDeathgasp
  - type: Cuffable
  - type: RotationVisuals
    defaultRotation: 90
    horizontalRotation: 90
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 80
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Stripping
  - type: Sprite
    drawdepth: Mobs
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: monkey
      sprite: Mobs/Animals/monkey.rsi
    - map: [ "jumpsuit" ]
    - map: [ "enum.HumanoidVisualLayers.Handcuffs" ]
      color: "#ffffff"
      sprite: Objects/Misc/handcuffs.rsi
      state: body-overlay-2
      visible: false
    - map: [ "ears" ]
    - map: [ "id" ]
    - map: [ "outerClothing" ]
    - map: [ "mask" ]
    - map: [ "head" ]
    - map: [ "clownedon" ]
      sprite: "Effects/creampie.rsi"
      state: "creampie_human"
      visible: false
  - type: Hands
  - type: ComplexInteraction
  - type: GenericVisualizer
    visuals:
      enum.CreamPiedVisuals.Creamed:
        clownedon:
          True: {visible: true}
          False: {visible: false}
  - type: Body
    prototype: Primate
    requiredLegs: 1 # TODO: More than 1 leg
  - type: CreamPied
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Monkey_burning
  - type: InteractionPopup
    successChance: 0.9
    interactSuccessString: petting-success-monkey
    interactFailureString: petting-failure-monkey
    interactSuccessSpawn: EffectHearts
    interactSuccessSound:
      path: /Audio/Animals/ferret_happy.ogg
    interactFailureSound:
      path: /Audio/Items/wirecutter.ogg
  - type: MeleeWeapon
    soundHit:
      path: /Audio/Effects/bite.ogg
    angle: 30
    animation: WeaponArcBite
    damage:
      types:
        Blunt: 3
        Piercing: 3
  - type: Butcherable
    butcheringType: Spike
    spawned:
    - id: FoodMeat
      amount: 3
  - type: Puller
    needsHands: false
  - type: CanHostGuardian
  - type: NPCRetaliation
    attackMemoryLength: 10
  - type: FactionException
  - type: NpcFactionMember
    factions:
      - Passive
  - type: HTN
    rootTask:
      task: SimpleHostileCompound
  - type: IdExaminable
  - type: Tag
    tags:
    - VimPilot
    - DoorBumpOpener
    - AnomalyHost
  - type: Reactive
    groups:
      Flammable: [ Touch ]
      Extinguish: [ Touch ]
    reactions:
    - reagents: [ Water, SpaceCleaner ]
      methods: [ Touch ]
      effects:
      - !type:WashCreamPieReaction

# Used for entities that are considered flying,
# i.e. shouldnt slip, have free movement in weightlesness, and should go over chasms/lava
- type: entity
  id: FlyingMobBase
  abstract: true
  components:
  - type: Physics
    bodyStatus: InAir
  - type: NoSlip
  - type: MovementAlwaysTouching
  - type: CanMoveInAir
  - type: MovementSpeedModifier
